export type SignalType = 'BREAKOUT' | 'SETUP' | 'COILING' | 'WATCH' | 'HOLD' | 'SELL' | 'STRONG_SELL';
export type PositionSignal = 'ADD' | 'HOLD' | 'REDUCE' | 'SELL';

export interface StockAnalysis {
  ticker: string;
  signal: SignalType;
  momentum_score: number;
  price?: number;
  rsi: number;
  macd_histogram: number;
  bb_position: number;
  atr_pct: number;
  volume_ratio: number;
  ma10: number; ma20: number; ma50: number; ma200: number;
  above_ma_count: number;
  stacked_bull: boolean;
  stacked_bear: boolean;
  setup_score?: number;
  setup_label?: string;
  setup_stage?: number;
  setup_base_weeks?: number;
  setup_atr_contraction?: number;
  setup_price_range?: number;
  setup_vol_drying?: boolean;
  setup_rs_leading?: boolean;
  setup_dist_pivot?: number;
  setup_is_coiling?: boolean;
  setup_detail?: string;
  vcp_score: number;
  vcp_is_vcp: boolean;
  vcp_pivot?: number | null;
  vcp_detail: string;
  vcp_contraction_count: number;
  vcp_base_weeks: number;
  vcp_last_pullback: number;
  vcp_lowest_vol: boolean;
  pivot_broken: boolean;
  pivot_dist: number;
  pivot_within_chase: boolean;
  breakout_52w: boolean;
  breakout_52w_day: number;
  breakout_52w_vol: boolean;
  breakout_52w_detail: string;
  obv_trend: 'UP' | 'DOWN' | 'FLAT';
  obv_detail: string;
  rs_vs_index: 'STRONG' | 'NEUTRAL' | 'WEAK';
  rs_vs_sector: 'STRONG' | 'NEUTRAL' | 'WEAK';
  rs_line_trend: 'UP' | 'DOWN' | 'FLAT';
  rs_line_divergence: 'BULLISH' | 'BEARISH' | 'NONE';
  rs_line_3m_change: number;
  rs_line_detail: string;
  rs_line_new_high: boolean;
  rs_line_spy_new_low: boolean;
  ma50_status: 'ABOVE' | 'AT' | 'BELOW';
  weekly_trend?: 'UPTREND' | 'DOWNTREND' | 'SIDEWAYS' | null;
  weekly_align_score?: number | null;
  weekly_is_entry?: boolean;
  weekly_pullback?: number | null;
  weekly_above_mas?: boolean;
  weekly_detail?: string | null;
  weekly_rsi?: number | null;
  pocket_pivot: boolean;
  pocket_pivot_days_ago: number;
  pocket_pivot_vol_ratio: number;
  pocket_pivot_above_ma: string | null;
  pocket_pivot_detail: string;
  short_pct?: number | null;
  short_squeeze?: 'HIGH' | 'MEDIUM' | 'LOW';
  short_detail?: string | null;
  entry_zone?: string | null;
  key_support?: string;
  key_resistance?: string;
  stop_loss?: string | null;
  rr_ratio?: number | null;
  rr_grade?: 'EXCELLENT' | 'GOOD' | 'FAIR' | 'POOR' | null;
  rr_risk?: number | null;
  rr_reward?: number | null;
  rr_label?: string;
  trail_initial_stop?: number | null;
  trail_stop_10?: number | null;
  trail_stop_20?: number | null;
  trail_stop_30?: number | null;
  trail_multiplier?: number | null;
  trail_break_even?: number | null;
  split_entry1?: { price: string; ratio: number; condition: string } | null;
  split_entry2?: { price: string; ratio: number; condition: string } | null;
  split_entry3?: { price: string; ratio: number; condition: string } | null;
  split_exit1?: { price: string; ratio: number; gain: string } | null;
  split_exit2?: { price: string; ratio: number; gain: string } | null;
  split_exit3?: { price: string; ratio: number; gain: string } | null;
  split_avg_entry?: number | null;
  pead_signal: boolean;
  pead_surprise_pct?: number | null;
  pead_detail?: string | null;
  regime_note?: string | null;
  rs_rank?: number;
  sector?: string | null;
  industry?: string | null;
  sector_warning?: string;
  summary: string;
  caution?: string | null;
  pattern: string;
  confidence: 'HIGH' | 'MEDIUM' | 'LOW';
}

export interface Position {
  id: string;
  ticker: string;
  avgPrice: number;
  shares: number;
  note?: string;
  isLeverage: boolean;
  leverageBase?: string;
  leverageMultiplier?: number;
  baseAtPurchase?: number;
}

export interface PositionResult extends Position {
  currentPrice: number;
  pnlPct: number;
  pnlAmt: number;
  totalValue: number;
  score: number;
  signal: PositionSignal;
  signalReason: string;
  entryZone?: string | null;
  stopLoss?: string | null;
  rsi?: number;
  macdBull?: boolean;
  stage?: number;
  impliedBasePrice?: number;
  stockData?: StockAnalysis;
}
